name: Credlawn
description: "Credlawn CRM."
publish_to: 'Credlawn India Private Limited'

version: 2.8.1+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pocketbase: ^0.24.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  device_info_plus: ^13.2.0
  android_id: ^0.5.1
  google_fonts: ^8.0.2
  font_awesome_flutter: ^11.0.0
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.0
  cached_network_image: ^3.4.1
  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^12.0.1
  call_log: ^6.0.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  uuid: ^4.3.3
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^22.2.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.16.0
  package_info_plus: ^10.2.1
  screenshot: ^3.0.0
  share_plus: ^13.3.0
  dio: ^5.7.0
  open_file: ^4.0.0
  file_picker: ^12.0.0-beta.7
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.24.2
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/splash.png"
    color: "#ffffff"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
